=== DucPM88/THHT/.mule/plugins-tmp/mule-slack-connector-4.2.2-mule-plugin/metadata/attachments-schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "definitions": {},
  "id": "Attachment",
  "items": {
    "id": "/items",
    "properties": {
      "actions": {
        "id": "/items/properties/actions",
        "items": {
          "id": "/items/properties/actions/items",
          "properties": {
            "name": {
              "id": "/items/properties/actions/items/properties/name",
              "type": "string"
            },
            "text": {
              "id": "/items/properties/actions/items/properties/text",
              "type": "string"
            },
            "type": {
              "id": "/items/properties/actions/items/properties/type",
              "type": "string"
            },
            "value": {
              "id": "/items/properties/actions/items/properties/value",
              "type": "string"
            }
          },
          "type": "object"
        },
        "type": "array"
      },
      "author_icon": {
        "id": "/items/properties/author_icon",
        "type": "string"
      },
      "author_link": {
        "id": "/items/properties/author_link",
        "type": "string"
      },
      "author_name": {
        "id": "/items/properties/author_name",
        "type": "string"
      },
      "color": {
        "id": "/items/properties/color",
        "type": "string"
      },
      "callback_id": {
        "id": "/items/properties/callback_id",
        "type": "string"
      },
      "fallback": {
        "id": "/items/properties/fallback",
        "type": "string"
      },
      "fields": {
        "id": "/items/properties/fields",
        "items": {
          "id": "/items/properties/fields/items",
          "properties": {
            "short": {
              "id": "/items/properties/fields/items/properties/short",
              "type": "boolean"
            },
            "title": {
              "id": "/items/properties/fields/items/properties/title",
              "type": "string"
            },
            "value": {
              "id": "/items/properties/fields/items/properties/value",
              "type": "string"
            }
          },
          "type": "object"
        },
        "type": "array"
      },
      "footer": {
        "id": "/items/properties/footer",
        "type": "string"
      },
      "footer_icon": {
        "id": "/items/properties/footer_icon",
        "type": "string"
      },
      "image_url": {
        "id": "/items/properties/image_url",
        "type": "string"
      },
      "mrkdwn_in": {
        "id": "/items/properties/mrkdwn_in",
        "items": {
          "id": "/items/properties/mrkdwn_in/items",
          "type": "string"
        },
        "type": "array"
      },
      "pretext": {
        "id": "/items/properties/pretext",
        "type": "string"
      },
      "text": {
        "id": "/items/properties/text",
        "type": "string"
      },
      "thumb_url": {
        "id": "/items/properties/thumb_url",
        "type": "string"
      },
      "title": {
        "id": "/items/properties/title",
        "type": "string"
      },
      "title_link": {
        "id": "/items/properties/title_link",
        "type": "string"
      },
      "ts": {
        "id": "/items/properties/ts",
        "type": "integer"
      }
    },
    "type": "object"
  },
  "type": "array"
}

=== DucPM88/THHT/.mule/plugins-tmp/mule-slack-connector-4.2.2-mule-plugin/metadata/attachments-example.json
[
  {
    "fallback": "Required plain-text summary of the attachment.",
    "color": "#36a64f",
    "pretext": "Optional text that appears above the attachment block",
    "author_name": "Bobby Tables",
    "author_link": "http://flickr.com/bobby/",
    "author_icon": "http://flickr.com/icons/bobby.jpg",
    "title": "Slack API Documentation",
    "title_link": "https://api.slack.com/",
    "text": "Optional text that appears within the attachment",
    "mrkdwn_in": [
      "text",
      "pretext"
    ],
    "fields": [
      {
        "title": "Priority",
        "value": "High",
        "short": false
      }
    ],
    "actions": [
      {
        "name": "game",
        "text": "Chess",
        "type": "button",
        "value": "chess"
      },
      {
        "name": "game",
        "text": "Falken's Maze",
        "type": "button",
        "value": "maze"
      },
      {
        "name": "game",
        "text": "Thermonuclear War",
        "style": "danger",
        "type": "button",
        "value": "war",
        "confirm": {
          "title": "Are you sure?",
          "text": "Wouldn't you prefer a good game of chess?",
          "ok_text": "Yes",
          "dismiss_text": "No"
        }
      },
      {
        "name": "games_list",
        "text": "Pick a game...",
        "type": "select",
        "options": [
          {
            "text": "Hearts",
            "value": "hearts"
          },
          {
            "text": "Bridge",
            "value": "bridge"
          },
          {
            "text": "Checkers",
            "value": "checkers"
          },
          {
            "text": "Chess",
            "value": "chess"
          },
          {
            "text": "Poker",
            "value": "poker"
          },
          {
            "text": "Falken's Maze",
            "value": "maze"
          },
          {
            "text": "Global Thermonuclear War",
            "value": "war"
          }
        ]
      }
    ],
    "image_url": "http://my-website.com/path/to/image.jpg",
    "thumb_url": "http://example.com/path/to/thumb.png",
    "footer": "Slack API",
    "footer_icon": "https://platform.slack-edge.com/img/default_application_icon.png",
    "ts": 123456789
  }
]
